-- MySQL Script generated by MySQL Workbench
-- Fri Jun 27 22:53:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema novo_banco
-- -----------------------------------------------------




-- -----------------------------------------------------
-- Table `tbl_carga_promover`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_carga_promover` ;

CREATE TABLE IF NOT EXISTS `tbl_carga_promover` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `data_fim_processo` DATETIME(6) NULL DEFAULT NULL,
  `data_inicio_processo` DATETIME(6) NULL DEFAULT NULL,
  `data_fim_carga` DATETIME(6) NULL DEFAULT NULL,
  `data_inicio_carga` DATETIME(6) NULL DEFAULT NULL,
  `nota` TEXT NULL DEFAULT NULL,
  `requisicao` TEXT NULL DEFAULT NULL,
  `status` ENUM('ERRO', 'PROCESSADO', 'PROCESSAR') NULL DEFAULT NULL,
  `uuid_requisicao` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_usuario` ;

CREATE TABLE IF NOT EXISTS `tbl_usuario` (
  `id` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `expira` DATETIME(6) NULL DEFAULT NULL,
  `habilitado` BIT(1) NOT NULL,
  `tipo` ENUM('ADMONISTRADOR', 'NORMAL') NULL DEFAULT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `UK2d7cmsnccdww0gvoib40t9v4a` ON `tbl_usuario` (`usuario` ASC) VISIBLE;

CREATE UNIQUE INDEX `UKdnvgup8yi2egdo5j5ekna9272` ON `tbl_usuario` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tbl_empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_empresa` ;

CREATE TABLE IF NOT EXISTS `tbl_empresa` (
  `id` VARCHAR(255) NOT NULL,
  `alterado` DATETIME(6) NULL DEFAULT NULL,
  `criado` DATETIME(6) NOT NULL,
  `ip_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_criador` VARCHAR(100) NOT NULL,
  `ip_proxy_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_proxy_criador` VARCHAR(100) NULL DEFAULT NULL,
  `status_dado` ENUM('APROVADO', 'NOVO', 'REMOVIDO', 'REPROVADO') NULL DEFAULT NULL,
  `cnpj` VARCHAR(200) NULL DEFAULT NULL,
  `nome` VARCHAR(250) NULL DEFAULT NULL,
  `principal` TINYINT(1) NULL DEFAULT '1',
  `id_usuario_alterado` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario_criador` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK4s48uu8o196i7livoy1xg2lly`
    FOREIGN KEY (`id_usuario_criador`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FKi4remo7l8nv8b9sowiiadwk1h`
    FOREIGN KEY (`id_usuario_alterado`)
    REFERENCES `tbl_usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `UKbr4qlws80djuskqf7skhholpr` ON `tbl_empresa` (`cnpj` ASC) VISIBLE;

CREATE INDEX `FKi4remo7l8nv8b9sowiiadwk1h` ON `tbl_empresa` (`id_usuario_alterado` ASC) VISIBLE;

CREATE INDEX `FK4s48uu8o196i7livoy1xg2lly` ON `tbl_empresa` (`id_usuario_criador` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tbl_configuracao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_configuracao` ;

CREATE TABLE IF NOT EXISTS `tbl_configuracao` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `alterado` DATETIME(6) NULL DEFAULT NULL,
  `criado` DATETIME(6) NOT NULL,
  `ip_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_criador` VARCHAR(100) NOT NULL,
  `ip_proxy_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_proxy_criador` VARCHAR(100) NULL DEFAULT NULL,
  `status_dado` ENUM('APROVADO', 'NOVO', 'REMOVIDO', 'REPROVADO') NULL DEFAULT NULL,
  `instagram` VARCHAR(250) NULL DEFAULT NULL,
  `site` VARCHAR(250) NULL DEFAULT NULL,
  `youtube` VARCHAR(250) NULL DEFAULT NULL,
  `id_usuario_alterado` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario_criador` VARCHAR(255) NOT NULL,
  `id_empresa` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK1tyh0l31u50daxnix4a0yhl97`
    FOREIGN KEY (`id_usuario_alterado`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FKjssph4xwh06rmtvi7623xbh5w`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `tbl_empresa` (`id`),
  CONSTRAINT `FKkb69x9ru59y8br3fegkao0hdi`
    FOREIGN KEY (`id_usuario_criador`)
    REFERENCES `tbl_usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `UKd0gem4vmu7uneltx4bmdck2f4` ON `tbl_configuracao` (`id_empresa` ASC) VISIBLE;

CREATE INDEX `FK1tyh0l31u50daxnix4a0yhl97` ON `tbl_configuracao` (`id_usuario_alterado` ASC) VISIBLE;

CREATE INDEX `FKkb69x9ru59y8br3fegkao0hdi` ON `tbl_configuracao` (`id_usuario_criador` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tbl_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_categoria` ;

CREATE TABLE IF NOT EXISTS `tbl_categoria` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `alias` VARCHAR(250) NOT NULL,
  `id_joomla` BIGINT NOT NULL,
  `id_wordpress` BIGINT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `usar_prompts` TINYINT(1) NULL DEFAULT '1',
  `id_configuracao` BIGINT NOT NULL,
  `id_pai` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK7kctuujr645wps9xaxx4yo849`
    FOREIGN KEY (`id_pai`)
    REFERENCES `tbl_categoria` (`id`),
  CONSTRAINT `FKrava8g9but5avsp1q0ssyd0bk`
    FOREIGN KEY (`id_configuracao`)
    REFERENCES `tbl_configuracao` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `UK2tdmgs8t56p3myi6yrsqm1p89` ON `tbl_categoria` (`id_joomla` ASC) VISIBLE;

CREATE UNIQUE INDEX `UKt0en8rgihwbl8wsoejsttf349` ON `tbl_categoria` (`id_wordpress` ASC) VISIBLE;

CREATE INDEX `FKrava8g9but5avsp1q0ssyd0bk` ON `tbl_categoria` (`id_configuracao` ASC) VISIBLE;

CREATE INDEX `FK7kctuujr645wps9xaxx4yo849` ON `tbl_categoria` (`id_pai` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tbl_chatgpt_treinamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_chatgpt_treinamento` ;

CREATE TABLE IF NOT EXISTS `tbl_chatgpt_treinamento` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `alterado` DATETIME(6) NULL DEFAULT NULL,
  `criado` DATETIME(6) NOT NULL,
  `ip_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_criador` VARCHAR(100) NOT NULL,
  `ip_proxy_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_proxy_criador` VARCHAR(100) NULL DEFAULT NULL,
  `status_dado` ENUM('APROVADO', 'NOVO', 'REMOVIDO', 'REPROVADO') NULL DEFAULT NULL,
  `audiencias` VARBINARY(255) NOT NULL,
  `especialista` VARBINARY(255) NOT NULL,
  `falhas` VARBINARY(255) NULL DEFAULT NULL,
  `redes_sociais` VARBINARY(255) NOT NULL,
  `site` VARCHAR(250) NOT NULL,
  `id_usuario_alterado` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario_criador` VARCHAR(255) NOT NULL,
  `id_configuracao` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK2irh98y2v8cc1vddvdlb3g3v3`
    FOREIGN KEY (`id_usuario_alterado`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FK6y3q6o0vhjo0flyalw8b0qn04`
    FOREIGN KEY (`id_usuario_criador`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FKpcbecdqfobvmac7e29vynoaru`
    FOREIGN KEY (`id_configuracao`)
    REFERENCES `tbl_configuracao` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `UKeblsbn3719bkfbsbbrfj7q9is` ON `tbl_chatgpt_treinamento` (`id_configuracao` ASC) VISIBLE;

CREATE INDEX `FK2irh98y2v8cc1vddvdlb3g3v3` ON `tbl_chatgpt_treinamento` (`id_usuario_alterado` ASC) VISIBLE;

CREATE INDEX `FK6y3q6o0vhjo0flyalw8b0qn04` ON `tbl_chatgpt_treinamento` (`id_usuario_criador` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tbl_chatgpt_perguntas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_chatgpt_perguntas` ;

CREATE TABLE IF NOT EXISTS `tbl_chatgpt_perguntas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `alterado` DATETIME(6) NULL DEFAULT NULL,
  `criado` DATETIME(6) NOT NULL,
  `ip_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_criador` VARCHAR(100) NOT NULL,
  `ip_proxy_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_proxy_criador` VARCHAR(100) NULL DEFAULT NULL,
  `status_dado` ENUM('APROVADO', 'NOVO', 'REMOVIDO', 'REPROVADO') NULL DEFAULT NULL,
  `complemento_formato_pedir_materia` VARCHAR(255) NULL DEFAULT NULL,
  `falhas` VARBINARY(255) NULL DEFAULT NULL,
  `pedir_dados_materia` VARCHAR(255) NOT NULL,
  `pedir_dados_materia_seguinte` VARCHAR(255) NULL DEFAULT NULL,
  `id_organization` VARCHAR(250) NOT NULL,
  `pedir_perguntas` VARCHAR(255) NOT NULL,
  `id_usuario_alterado` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario_criador` VARCHAR(255) NOT NULL,
  `id_chatgpt_configuracao` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FKj1fu8e1ogii0d2xnvl7x2jmg`
    FOREIGN KEY (`id_usuario_alterado`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FKksk15us72epl68nc04vxamyhn`
    FOREIGN KEY (`id_usuario_criador`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FKonsn6rhmwets30fbju5tyvetf`
    FOREIGN KEY (`id_chatgpt_configuracao`)
    REFERENCES `tbl_chatgpt_treinamento` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKj1fu8e1ogii0d2xnvl7x2jmg` ON `tbl_chatgpt_perguntas` (`id_usuario_alterado` ASC) VISIBLE;

CREATE INDEX `FKksk15us72epl68nc04vxamyhn` ON `tbl_chatgpt_perguntas` (`id_usuario_criador` ASC) VISIBLE;

CREATE INDEX `FKonsn6rhmwets30fbju5tyvetf` ON `tbl_chatgpt_perguntas` (`id_chatgpt_configuracao` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tbl_chtgpt_configuracao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_chtgpt_configuracao` ;

CREATE TABLE IF NOT EXISTS `tbl_chtgpt_configuracao` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `alterado` DATETIME(6) NULL DEFAULT NULL,
  `criado` DATETIME(6) NOT NULL,
  `ip_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_criador` VARCHAR(100) NOT NULL,
  `ip_proxy_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_proxy_criador` VARCHAR(100) NULL DEFAULT NULL,
  `status_dado` ENUM('APROVADO', 'NOVO', 'REMOVIDO', 'REPROVADO') NULL DEFAULT NULL,
  `id_assistente` VARCHAR(250) NULL DEFAULT NULL,
  `bearer` VARCHAR(250) NOT NULL,
  `max_tokens` VARCHAR(250) NOT NULL,
  `model` VARCHAR(250) NOT NULL,
  `id_organization` VARCHAR(250) NOT NULL,
  `role_assistant` VARCHAR(250) NOT NULL,
  `role_system` VARCHAR(250) NOT NULL,
  `role_user` VARCHAR(250) NOT NULL,
  `temperature` DOUBLE NOT NULL,
  `id_thrend` VARCHAR(200) NULL DEFAULT NULL,
  `id_usuario_alterado` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario_criador` VARCHAR(255) NOT NULL,
  `id_configuracao` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FKelps9h8a2murtyhjm2cpf0gyq`
    FOREIGN KEY (`id_usuario_criador`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FKm7gbfj3has9p5qufxwjn0ypp0`
    FOREIGN KEY (`id_configuracao`)
    REFERENCES `tbl_configuracao` (`id`),
  CONSTRAINT `FKqqqvu0koe8nn6qy3mrbwrusuh`
    FOREIGN KEY (`id_usuario_alterado`)
    REFERENCES `tbl_usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `UKnnj0t7kioclutlf4hb6voruk2` ON `tbl_chtgpt_configuracao` (`id_configuracao` ASC) VISIBLE;

CREATE INDEX `FKqqqvu0koe8nn6qy3mrbwrusuh` ON `tbl_chtgpt_configuracao` (`id_usuario_alterado` ASC) VISIBLE;

CREATE INDEX `FKelps9h8a2murtyhjm2cpf0gyq` ON `tbl_chtgpt_configuracao` (`id_usuario_criador` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tbl_configuracao_joomla`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_configuracao_joomla` ;

CREATE TABLE IF NOT EXISTS `tbl_configuracao_joomla` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `alterado` DATETIME(6) NULL DEFAULT NULL,
  `criado` DATETIME(6) NOT NULL,
  `ip_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_criador` VARCHAR(100) NOT NULL,
  `ip_proxy_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_proxy_criador` VARCHAR(100) NULL DEFAULT NULL,
  `status_dado` ENUM('APROVADO', 'NOVO', 'REMOVIDO', 'REPROVADO') NULL DEFAULT NULL,
  `bearer` VARCHAR(250) NOT NULL,
  `idioma` VARCHAR(100) NULL DEFAULT NULL,
  `rul` VARCHAR(250) NOT NULL,
  `senha` VARCHAR(100) NULL DEFAULT NULL,
  `url` VARCHAR(250) NOT NULL,
  `usuario` VARCHAR(100) NULL DEFAULT NULL,
  `id_usuario_alterado` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario_criador` VARCHAR(255) NOT NULL,
  `id_configuracao` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK4wqn1lmqyxe5tpqcf42qk013`
    FOREIGN KEY (`id_usuario_criador`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FK8h9ykt5xdll412bpw5w87mc9f`
    FOREIGN KEY (`id_configuracao`)
    REFERENCES `tbl_configuracao` (`id`),
  CONSTRAINT `FKtn7nxu40kd4vccikdnql25x7g`
    FOREIGN KEY (`id_usuario_alterado`)
    REFERENCES `tbl_usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `UK1p64fs1xaliewncm69y4a8aw7` ON `tbl_configuracao_joomla` (`id_configuracao` ASC) VISIBLE;

CREATE INDEX `FKtn7nxu40kd4vccikdnql25x7g` ON `tbl_configuracao_joomla` (`id_usuario_alterado` ASC) VISIBLE;

CREATE INDEX `FK4wqn1lmqyxe5tpqcf42qk013` ON `tbl_configuracao_joomla` (`id_usuario_criador` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tbl_mapa_perguntas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_mapa_perguntas` ;

CREATE TABLE IF NOT EXISTS `tbl_mapa_perguntas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `data_sugestao_publicacao` DATE NULL DEFAULT NULL,
  `motivo_sugestao` VARCHAR(3000) NULL DEFAULT NULL,
  `ordem_relevancia` INT NULL DEFAULT NULL,
  `perfil_enquadra` VARCHAR(3000) NULL DEFAULT NULL,
  `pergunta` VARCHAR(250) NOT NULL,
  `stream` TEXT NULL DEFAULT NULL,
  `uuid_requisicao` VARCHAR(100) NULL DEFAULT NULL,
  `id_categoria` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK6at2bbxs6y1obm4j022w5apwh`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `tbl_categoria` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK6at2bbxs6y1obm4j022w5apwh` ON `tbl_mapa_perguntas` (`id_categoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tbl_materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_materia` ;

CREATE TABLE IF NOT EXISTS `tbl_materia` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `alias` VARCHAR(500) NULL DEFAULT NULL,
  `cricao_banco` DATETIME(6) NULL DEFAULT NULL,
  `cricao_na_plataforma` DATETIME(6) NULL DEFAULT NULL,
  `exportado_para_plataforma` DATETIME(6) NULL DEFAULT NULL,
  `id_joomla` BIGINT NULL DEFAULT NULL,
  `id_wordpress` BIGINT NULL DEFAULT NULL,
  `keywords` VARCHAR(250) NULL DEFAULT NULL,
  `materia` TEXT NULL DEFAULT NULL,
  `meta_descircao` VARCHAR(250) NULL DEFAULT NULL,
  `introducao` VARCHAR(250) NULL DEFAULT NULL,
  `data_publicar` DATETIME(6) NULL DEFAULT NULL,
  `status` ENUM('ERRO', 'PROCESSADO', 'PROCESSAR') NULL DEFAULT NULL,
  `stream` TEXT NULL DEFAULT NULL,
  `tema_proposto` VARCHAR(250) NULL DEFAULT NULL,
  `titulo_1` VARCHAR(200) NULL DEFAULT NULL,
  `titulo_2` VARCHAR(200) NULL DEFAULT NULL,
  `titulo_3` VARCHAR(200) NULL DEFAULT NULL,
  `titulo_selecionado` INT NULL DEFAULT NULL,
  `uuid_requisicao` VARCHAR(100) NULL DEFAULT NULL,
  `id_categoria` BIGINT NULL DEFAULT NULL,
  `id_configuracao` BIGINT NOT NULL,
  `id_mapa_pergunta` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FKg4yusl8tft5wwuh14iufhjsmw`
    FOREIGN KEY (`id_configuracao`)
    REFERENCES `tbl_configuracao` (`id`),
  CONSTRAINT `FKhndfhxnwmhkmqd11wkn8ahxvc`
    FOREIGN KEY (`id_mapa_pergunta`)
    REFERENCES `tbl_mapa_perguntas` (`id`),
  CONSTRAINT `FKlya3s7h1f2xri63qkygoq1c8d`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `tbl_categoria` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `IDX8vedxu0p67yrs9131895j5wr5` ON `tbl_materia` (`titulo_1` ASC, `titulo_2` ASC, `titulo_3` ASC, `cricao_banco` ASC) VISIBLE;

CREATE INDEX `IDXsb22hyflx7n2n5cpax5ei7huo` ON `tbl_materia` (`titulo_1` ASC, `titulo_2` ASC, `titulo_3` ASC) VISIBLE;

CREATE INDEX `IDXg4lmns22ccv5v7t93vrbdhu6m` ON `tbl_materia` (`cricao_banco` ASC) VISIBLE;

CREATE INDEX `FKlya3s7h1f2xri63qkygoq1c8d` ON `tbl_materia` (`id_categoria` ASC) VISIBLE;

CREATE INDEX `FKg4yusl8tft5wwuh14iufhjsmw` ON `tbl_materia` (`id_configuracao` ASC) VISIBLE;

CREATE INDEX `FKhndfhxnwmhkmqd11wkn8ahxvc` ON `tbl_materia` (`id_mapa_pergunta` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tbl_dialogo_chatgpt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_dialogo_chatgpt` ;

CREATE TABLE IF NOT EXISTS `tbl_dialogo_chatgpt` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `completion_tokens` BIGINT NULL DEFAULT NULL,
  `resposta` TEXT NOT NULL,
  `created` BIGINT NULL DEFAULT NULL,
  `dt_criacao` DATETIME(6) NOT NULL,
  `finish_reason` VARCHAR(200) NULL DEFAULT NULL,
  `id_chatgpt` VARCHAR(200) NULL DEFAULT NULL,
  `index_chatgpt` INT NULL DEFAULT NULL,
  `dt_inicio_processamento` DATETIME(6) NOT NULL,
  `logprobs` VARCHAR(200) NULL DEFAULT NULL,
  `model` VARCHAR(200) NULL DEFAULT NULL,
  `objeto` VARCHAR(200) NULL DEFAULT NULL,
  `pergunta` TEXT NOT NULL,
  `prompt_tokens` BIGINT NULL DEFAULT NULL,
  `role` VARCHAR(200) NULL DEFAULT NULL,
  `system_fingerprint` VARCHAR(200) NULL DEFAULT NULL,
  `total_tokens` BIGINT NULL DEFAULT NULL,
  `uuid` VARCHAR(200) NOT NULL,
  `id_materia` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FKiyvlk02qiyqsww7rvonmttwsv`
    FOREIGN KEY (`id_materia`)
    REFERENCES `tbl_materia` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKiyvlk02qiyqsww7rvonmttwsv` ON `tbl_dialogo_chatgpt` (`id_materia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tbl_faq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_faq` ;

CREATE TABLE IF NOT EXISTS `tbl_faq` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `pergunta` VARCHAR(250) NOT NULL,
  `resposta` VARCHAR(250) NOT NULL,
  `uuid_requisicao` VARCHAR(250) NULL DEFAULT NULL,
  `id_configuracao` BIGINT NOT NULL,
  `id_materia` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FKj2yyl1na9upfv0na6yhagae12`
    FOREIGN KEY (`id_configuracao`)
    REFERENCES `tbl_configuracao` (`id`),
  CONSTRAINT `FKjyvq9wat1t1k0l67xckhxjhv6`
    FOREIGN KEY (`id_materia`)
    REFERENCES `tbl_materia` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKj2yyl1na9upfv0na6yhagae12` ON `tbl_faq` (`id_configuracao` ASC) VISIBLE;

CREATE INDEX `FKjyvq9wat1t1k0l67xckhxjhv6` ON `tbl_faq` (`id_materia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tbl_feriados_fixos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_feriados_fixos` ;

CREATE TABLE IF NOT EXISTS `tbl_feriados_fixos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `data_feriado` DATE NOT NULL,
  `nome_feriado` VARCHAR(255) NOT NULL,
  `tipo` ENUM('DATA_COMEMORATIVA', 'FERIADO_NORMAL', 'OUTRO') NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_feriados_moveis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_feriados_moveis` ;

CREATE TABLE IF NOT EXISTS `tbl_feriados_moveis` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `data_feriado` DATE NOT NULL,
  `nome_feriado` VARCHAR(255) NOT NULL,
  `tipo` ENUM('DATA_COMEMORATIVA', 'FERIADO_NORMAL', 'OUTRO') NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_grupo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_grupo_usuario` ;

CREATE TABLE IF NOT EXISTS `tbl_grupo_usuario` (
  `id` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `UKtnqir316fedkhyho1x8ri77i7` ON `tbl_grupo_usuario` (`nome` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tbl_permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_permissao` ;

CREATE TABLE IF NOT EXISTS `tbl_permissao` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `UKrwdply7c46irf2085g0mekykp` ON `tbl_permissao` (`nome` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tbl_grupo_permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_grupo_permissao` ;

CREATE TABLE IF NOT EXISTS `tbl_grupo_permissao` (
  `id_permissao` BIGINT NOT NULL,
  `id_grupo` VARCHAR(255) NOT NULL,
  CONSTRAINT `FKbxh4h79wbdg8k452gsmkhx71u`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `tbl_grupo_usuario` (`id`),
  CONSTRAINT `FKjcqyyshxoblg8nrhhmtrx71f8`
    FOREIGN KEY (`id_permissao`)
    REFERENCES `tbl_permissao` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKbxh4h79wbdg8k452gsmkhx71u` ON `tbl_grupo_permissao` (`id_grupo` ASC) VISIBLE;

CREATE INDEX `FKjcqyyshxoblg8nrhhmtrx71f8` ON `tbl_grupo_permissao` (`id_permissao` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tbl_mapa_subperguntas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_mapa_subperguntas` ;

CREATE TABLE IF NOT EXISTS `tbl_mapa_subperguntas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `pergunta` VARCHAR(250) NOT NULL,
  `uuid_requisicao` VARCHAR(100) NULL DEFAULT NULL,
  `id_mapa_pergunta` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK6vxksxivggd7beidm41nocv9p`
    FOREIGN KEY (`id_mapa_pergunta`)
    REFERENCES `tbl_mapa_perguntas` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK6vxksxivggd7beidm41nocv9p` ON `tbl_mapa_subperguntas` (`id_mapa_pergunta` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tbl_mapaperguntas_termo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_mapaperguntas_termo` ;

CREATE TABLE IF NOT EXISTS `tbl_mapaperguntas_termo` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `termo` VARCHAR(250) NOT NULL,
  `uuid_requisicao` VARCHAR(100) NULL DEFAULT NULL,
  `id_mapa_pergunta` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK7xq16jd6665h16svsekteggnq`
    FOREIGN KEY (`id_mapa_pergunta`)
    REFERENCES `tbl_mapa_perguntas` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK7xq16jd6665h16svsekteggnq` ON `tbl_mapaperguntas_termo` (`id_mapa_pergunta` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tbl_materia_faqs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_materia_faqs` ;

CREATE TABLE IF NOT EXISTS `tbl_materia_faqs` (
  `materia_entity_id` BIGINT NOT NULL,
  `faqs_id` BIGINT NOT NULL,
  CONSTRAINT `FKltvsdsahbtge1mf7wy62e7d9r`
    FOREIGN KEY (`materia_entity_id`)
    REFERENCES `tbl_materia` (`id`),
  CONSTRAINT `FKmjlr3ej4298by2ndqi7tqrlf3`
    FOREIGN KEY (`faqs_id`)
    REFERENCES `tbl_faq` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `UK6rqvde6nlsxh88qui4tfya7ya` ON `tbl_materia_faqs` (`faqs_id` ASC) VISIBLE;

CREATE INDEX `FKltvsdsahbtge1mf7wy62e7d9r` ON `tbl_materia_faqs` (`materia_entity_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tbl_materia_log_processo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_materia_log_processo` ;

CREATE TABLE IF NOT EXISTS `tbl_materia_log_processo` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `stream_dados_materia` TEXT NOT NULL,
  `gerado_dados` DATETIME(6) NOT NULL,
  `gerado_materia` DATETIME(6) NOT NULL,
  `info_materia` TEXT NULL DEFAULT NULL,
  `stream_materia` TEXT NULL DEFAULT NULL,
  `id_configuracao` BIGINT NOT NULL,
  `id_materia` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK2j5k0y65gqnc4tevpfajnvcxh`
    FOREIGN KEY (`id_configuracao`)
    REFERENCES `tbl_configuracao` (`id`),
  CONSTRAINT `FKrrl9stpx56vx2n8gsuyr201yd`
    FOREIGN KEY (`id_materia`)
    REFERENCES `tbl_materia` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK2j5k0y65gqnc4tevpfajnvcxh` ON `tbl_materia_log_processo` (`id_configuracao` ASC) VISIBLE;

CREATE INDEX `FKrrl9stpx56vx2n8gsuyr201yd` ON `tbl_materia_log_processo` (`id_materia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tbl_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_tag` ;

CREATE TABLE IF NOT EXISTS `tbl_tag` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `alias` VARCHAR(250) NULL DEFAULT NULL,
  `id_joomla` BIGINT NULL DEFAULT NULL,
  `id_wordpress` BIGINT NULL DEFAULT NULL,
  `idioma` VARCHAR(250) NULL DEFAULT NULL,
  `titulo` VARCHAR(250) NOT NULL,
  `uuid_requisicao` VARCHAR(100) NULL DEFAULT NULL,
  `id_configuracao` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK90dnb79s0ini35hpcjb39siko`
    FOREIGN KEY (`id_configuracao`)
    REFERENCES `tbl_configuracao` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK90dnb79s0ini35hpcjb39siko` ON `tbl_tag` (`id_configuracao` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tbl_materia_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_materia_tags` ;

CREATE TABLE IF NOT EXISTS `tbl_materia_tags` (
  `id_tag` BIGINT NOT NULL,
  `tags_id` BIGINT NOT NULL,
  CONSTRAINT `FK73gk8n7365mm422c5q6owoms6`
    FOREIGN KEY (`id_tag`)
    REFERENCES `tbl_materia` (`id`),
  CONSTRAINT `FK9rgmqeajn1d0o260t7rlne9vg`
    FOREIGN KEY (`tags_id`)
    REFERENCES `tbl_tag` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK9rgmqeajn1d0o260t7rlne9vg` ON `tbl_materia_tags` (`tags_id` ASC) VISIBLE;

CREATE INDEX `FK73gk8n7365mm422c5q6owoms6` ON `tbl_materia_tags` (`id_tag` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tbl_termos_empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_termos_empresa` ;

CREATE TABLE IF NOT EXISTS `tbl_termos_empresa` (
  `id` VARCHAR(255) NOT NULL,
  `alterado` DATETIME(6) NULL DEFAULT NULL,
  `criado` DATETIME(6) NOT NULL,
  `ip_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_criador` VARCHAR(100) NOT NULL,
  `ip_proxy_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_proxy_criador` VARCHAR(100) NULL DEFAULT NULL,
  `status_dado` ENUM('APROVADO', 'NOVO', 'REMOVIDO', 'REPROVADO') NULL DEFAULT NULL,
  `nome` VARCHAR(250) NOT NULL,
  `id_usuario_alterado` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario_criador` VARCHAR(255) NOT NULL,
  `id_empresa` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK2kkxc397v71nskfr2dh9gbgvj`
    FOREIGN KEY (`id_usuario_criador`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FKk0v4trw0w3057jjtu4vjowd92`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `tbl_empresa` (`id`),
  CONSTRAINT `FKmym8cii3fxbcr2exay2ad7jo0`
    FOREIGN KEY (`id_usuario_alterado`)
    REFERENCES `tbl_usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKmym8cii3fxbcr2exay2ad7jo0` ON `tbl_termos_empresa` (`id_usuario_alterado` ASC) VISIBLE;

CREATE INDEX `FK2kkxc397v71nskfr2dh9gbgvj` ON `tbl_termos_empresa` (`id_usuario_criador` ASC) VISIBLE;

CREATE INDEX `FKk0v4trw0w3057jjtu4vjowd92` ON `tbl_termos_empresa` (`id_empresa` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tbl_usuario_empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_usuario_empresa` ;

CREATE TABLE IF NOT EXISTS `tbl_usuario_empresa` (
  `id_empresa` VARCHAR(255) NOT NULL,
  `id_usuario` VARCHAR(255) NOT NULL,
  CONSTRAINT `FKjacf7sqg6wbb1nk88x9nyvcy1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FKkfhl5iiqfi7bc72bcx8jgglga`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `tbl_empresa` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKjacf7sqg6wbb1nk88x9nyvcy1` ON `tbl_usuario_empresa` (`id_usuario` ASC) VISIBLE;

CREATE INDEX `FKkfhl5iiqfi7bc72bcx8jgglga` ON `tbl_usuario_empresa` (`id_empresa` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tbl_usuario_grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_usuario_grupo` ;

CREATE TABLE IF NOT EXISTS `tbl_usuario_grupo` (
  `id_usuario` VARCHAR(255) NOT NULL,
  `id_grupo` VARCHAR(255) NOT NULL,
  CONSTRAINT `FKiejsyprpu34t9b1ob3e7juoct`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FKm2q8clo9utv5lspv3yos3ghs1`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `tbl_grupo_usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKm2q8clo9utv5lspv3yos3ghs1` ON `tbl_usuario_grupo` (`id_grupo` ASC) VISIBLE;

CREATE INDEX `FKiejsyprpu34t9b1ob3e7juoct` ON `tbl_usuario_grupo` (`id_usuario` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
