-- MySQL Script generated by MySQL Workbench
-- Wed Jul  2 00:37:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `tbl_carga_promover`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_carga_promover` ;

CREATE TABLE IF NOT EXISTS `tbl_carga_promover` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `data_fim_processo` DATETIME(6) NULL DEFAULT NULL,
  `data_inicio_processo` DATETIME(6) NULL DEFAULT NULL,
  `data_fim_carga` DATETIME(6) NULL DEFAULT NULL,
  `data_inicio_carga` DATETIME(6) NULL DEFAULT NULL,
  `nota` TEXT NULL DEFAULT NULL,
  `requisicao` TEXT NULL DEFAULT NULL,
  `status` ENUM('ERRO', 'PROCESSADO', 'PROCESSAR') NULL DEFAULT NULL,
  `uuid_requisicao` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_usuario` ;

CREATE TABLE IF NOT EXISTS `tbl_usuario` (
  `id` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `expira` DATETIME(6) NULL DEFAULT NULL,
  `habilitado` BIT(1) NOT NULL,
  `tipo` ENUM('ADMINISTRADOR', 'NORMAL') NULL DEFAULT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK2d7cmsnccdww0gvoib40t9v4a` (`usuario` ASC) VISIBLE,
  UNIQUE INDEX `UKdnvgup8yi2egdo5j5ekna9272` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_empresa` ;

CREATE TABLE IF NOT EXISTS `tbl_empresa` (
  `id` VARCHAR(255) NOT NULL,
  `alterado` DATETIME(6) NULL DEFAULT NULL,
  `criado` DATETIME(6) NOT NULL,
  `ip_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_criador` VARCHAR(100) NOT NULL,
  `ip_proxy_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_proxy_criador` VARCHAR(100) NULL DEFAULT NULL,
  `status_dado` ENUM('APROVADO', 'NOVO', 'REMOVIDO', 'REPROVADO') NULL DEFAULT NULL,
  `cnpj` VARCHAR(18) NOT NULL,
  `nome` VARCHAR(250) NULL DEFAULT NULL,
  `principal` TINYINT(1) NULL DEFAULT '1',
  `id_usuario_alterado` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario_criador` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKbr4qlws80djuskqf7skhholpr` (`cnpj` ASC) VISIBLE,
  INDEX `FKi4remo7l8nv8b9sowiiadwk1h` (`id_usuario_alterado` ASC) VISIBLE,
  INDEX `FK4s48uu8o196i7livoy1xg2lly` (`id_usuario_criador` ASC) VISIBLE,
  CONSTRAINT `FK4s48uu8o196i7livoy1xg2lly`
    FOREIGN KEY (`id_usuario_criador`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FKi4remo7l8nv8b9sowiiadwk1h`
    FOREIGN KEY (`id_usuario_alterado`)
    REFERENCES `tbl_usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_configuracao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_configuracao` ;

CREATE TABLE IF NOT EXISTS `tbl_configuracao` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `alterado` DATETIME(6) NULL DEFAULT NULL,
  `criado` DATETIME(6) NOT NULL,
  `ip_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_criador` VARCHAR(100) NOT NULL,
  `ip_proxy_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_proxy_criador` VARCHAR(100) NULL DEFAULT NULL,
  `status_dado` ENUM('APROVADO', 'NOVO', 'REMOVIDO', 'REPROVADO') NULL DEFAULT NULL,
  `instagram` VARCHAR(250) NULL DEFAULT NULL,
  `site` VARCHAR(250) NULL DEFAULT NULL,
  `youtube` VARCHAR(250) NULL DEFAULT NULL,
  `id_usuario_alterado` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario_criador` VARCHAR(255) NOT NULL,
  `id_empresa` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKd0gem4vmu7uneltx4bmdck2f4` (`id_empresa` ASC) VISIBLE,
  INDEX `FK1tyh0l31u50daxnix4a0yhl97` (`id_usuario_alterado` ASC) VISIBLE,
  INDEX `FKkb69x9ru59y8br3fegkao0hdi` (`id_usuario_criador` ASC) VISIBLE,
  CONSTRAINT `FK1tyh0l31u50daxnix4a0yhl97`
    FOREIGN KEY (`id_usuario_alterado`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FKjssph4xwh06rmtvi7623xbh5w`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `tbl_empresa` (`id`),
  CONSTRAINT `FKkb69x9ru59y8br3fegkao0hdi`
    FOREIGN KEY (`id_usuario_criador`)
    REFERENCES `tbl_usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_categoria` ;

CREATE TABLE IF NOT EXISTS `tbl_categoria` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `alterado` DATETIME(6) NULL DEFAULT NULL,
  `criado` DATETIME(6) NOT NULL,
  `ip_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_criador` VARCHAR(100) NOT NULL,
  `ip_proxy_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_proxy_criador` VARCHAR(100) NULL DEFAULT NULL,
  `status_dado` ENUM('APROVADO', 'NOVO', 'REMOVIDO', 'REPROVADO') NULL DEFAULT NULL,
  `alias` VARCHAR(250) NOT NULL,
  `id_joomla` BIGINT NOT NULL,
  `id_wordpress` BIGINT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `usar_prompts` TINYINT(1) NULL DEFAULT '1',
  `id_usuario_alterado` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario_criador` VARCHAR(255) NOT NULL,
  `id_configuracao` BIGINT NOT NULL,
  `id_pai` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK2tdmgs8t56p3myi6yrsqm1p89` (`id_joomla` ASC) VISIBLE,
  UNIQUE INDEX `UKt0en8rgihwbl8wsoejsttf349` (`id_wordpress` ASC) VISIBLE,
  INDEX `FKjhsadu3ko0cfpv39sop2gsiai` (`id_usuario_alterado` ASC) VISIBLE,
  INDEX `FKomwnp27qtuac1dbcx7447qlf5` (`id_usuario_criador` ASC) VISIBLE,
  INDEX `FKrava8g9but5avsp1q0ssyd0bk` (`id_configuracao` ASC) VISIBLE,
  INDEX `FK7kctuujr645wps9xaxx4yo849` (`id_pai` ASC) VISIBLE,
  CONSTRAINT `FK7kctuujr645wps9xaxx4yo849`
    FOREIGN KEY (`id_pai`)
    REFERENCES `tbl_categoria` (`id`),
  CONSTRAINT `FKjhsadu3ko0cfpv39sop2gsiai`
    FOREIGN KEY (`id_usuario_alterado`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FKomwnp27qtuac1dbcx7447qlf5`
    FOREIGN KEY (`id_usuario_criador`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FKrava8g9but5avsp1q0ssyd0bk`
    FOREIGN KEY (`id_configuracao`)
    REFERENCES `tbl_configuracao` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_chatgpt_treinamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_chatgpt_treinamento` ;

CREATE TABLE IF NOT EXISTS `tbl_chatgpt_treinamento` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `alterado` DATETIME(6) NULL DEFAULT NULL,
  `criado` DATETIME(6) NOT NULL,
  `ip_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_criador` VARCHAR(100) NOT NULL,
  `ip_proxy_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_proxy_criador` VARCHAR(100) NULL DEFAULT NULL,
  `status_dado` ENUM('APROVADO', 'NOVO', 'REMOVIDO', 'REPROVADO') NULL DEFAULT NULL,
  `id_usuario_alterado` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario_criador` VARCHAR(255) NOT NULL,
  `id_configuracao` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKeblsbn3719bkfbsbbrfj7q9is` (`id_configuracao` ASC) VISIBLE,
  INDEX `FK2irh98y2v8cc1vddvdlb3g3v3` (`id_usuario_alterado` ASC) VISIBLE,
  INDEX `FK6y3q6o0vhjo0flyalw8b0qn04` (`id_usuario_criador` ASC) VISIBLE,
  CONSTRAINT `FK2irh98y2v8cc1vddvdlb3g3v3`
    FOREIGN KEY (`id_usuario_alterado`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FK6y3q6o0vhjo0flyalw8b0qn04`
    FOREIGN KEY (`id_usuario_criador`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FKpcbecdqfobvmac7e29vynoaru`
    FOREIGN KEY (`id_configuracao`)
    REFERENCES `tbl_configuracao` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_chatgpt_perguntas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_chatgpt_perguntas` ;

CREATE TABLE IF NOT EXISTS `tbl_chatgpt_perguntas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `alterado` DATETIME(6) NULL DEFAULT NULL,
  `criado` DATETIME(6) NOT NULL,
  `ip_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_criador` VARCHAR(100) NOT NULL,
  `ip_proxy_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_proxy_criador` VARCHAR(100) NULL DEFAULT NULL,
  `status_dado` ENUM('APROVADO', 'NOVO', 'REMOVIDO', 'REPROVADO') NULL DEFAULT NULL,
  `complemento_formato_pedir_materia` VARCHAR(255) NULL DEFAULT NULL,
  `falhas` VARBINARY(255) NULL DEFAULT NULL,
  `pedir_dados_materia` VARCHAR(255) NOT NULL,
  `pedir_dados_materia_seguinte` VARCHAR(255) NULL DEFAULT NULL,
  `id_organization` VARCHAR(250) NOT NULL,
  `pedir_perguntas` VARCHAR(255) NOT NULL,
  `id_usuario_alterado` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario_criador` VARCHAR(255) NOT NULL,
  `id_chatgpt_configuracao` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKj1fu8e1ogii0d2xnvl7x2jmg` (`id_usuario_alterado` ASC) VISIBLE,
  INDEX `FKksk15us72epl68nc04vxamyhn` (`id_usuario_criador` ASC) VISIBLE,
  INDEX `FKonsn6rhmwets30fbju5tyvetf` (`id_chatgpt_configuracao` ASC) VISIBLE,
  CONSTRAINT `FKj1fu8e1ogii0d2xnvl7x2jmg`
    FOREIGN KEY (`id_usuario_alterado`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FKksk15us72epl68nc04vxamyhn`
    FOREIGN KEY (`id_usuario_criador`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FKonsn6rhmwets30fbju5tyvetf`
    FOREIGN KEY (`id_chatgpt_configuracao`)
    REFERENCES `tbl_chatgpt_treinamento` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_chtgpt_configuracao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_chtgpt_configuracao` ;

CREATE TABLE IF NOT EXISTS `tbl_chtgpt_configuracao` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `alterado` DATETIME(6) NULL DEFAULT NULL,
  `criado` DATETIME(6) NOT NULL,
  `ip_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_criador` VARCHAR(100) NOT NULL,
  `ip_proxy_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_proxy_criador` VARCHAR(100) NULL DEFAULT NULL,
  `status_dado` ENUM('APROVADO', 'NOVO', 'REMOVIDO', 'REPROVADO') NULL DEFAULT NULL,
  `id_assistente` VARCHAR(250) NULL DEFAULT NULL,
  `bearer` VARCHAR(250) NOT NULL,
  `max_tokens` VARCHAR(250) NOT NULL,
  `model` VARCHAR(250) NOT NULL,
  `id_organization` VARCHAR(250) NOT NULL,
  `role_assistant` VARCHAR(250) NOT NULL,
  `role_system` VARCHAR(250) NOT NULL,
  `role_user` VARCHAR(250) NOT NULL,
  `temperature` DOUBLE NOT NULL,
  `id_thrend` VARCHAR(200) NULL DEFAULT NULL,
  `id_usuario_alterado` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario_criador` VARCHAR(255) NOT NULL,
  `id_configuracao` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKnnj0t7kioclutlf4hb6voruk2` (`id_configuracao` ASC) VISIBLE,
  INDEX `FKqqqvu0koe8nn6qy3mrbwrusuh` (`id_usuario_alterado` ASC) VISIBLE,
  INDEX `FKelps9h8a2murtyhjm2cpf0gyq` (`id_usuario_criador` ASC) VISIBLE,
  CONSTRAINT `FKelps9h8a2murtyhjm2cpf0gyq`
    FOREIGN KEY (`id_usuario_criador`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FKm7gbfj3has9p5qufxwjn0ypp0`
    FOREIGN KEY (`id_configuracao`)
    REFERENCES `tbl_configuracao` (`id`),
  CONSTRAINT `FKqqqvu0koe8nn6qy3mrbwrusuh`
    FOREIGN KEY (`id_usuario_alterado`)
    REFERENCES `tbl_usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_configuracao_joomla`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_configuracao_joomla` ;

CREATE TABLE IF NOT EXISTS `tbl_configuracao_joomla` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `alterado` DATETIME(6) NULL DEFAULT NULL,
  `criado` DATETIME(6) NOT NULL,
  `ip_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_criador` VARCHAR(100) NOT NULL,
  `ip_proxy_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_proxy_criador` VARCHAR(100) NULL DEFAULT NULL,
  `status_dado` ENUM('APROVADO', 'NOVO', 'REMOVIDO', 'REPROVADO') NULL DEFAULT NULL,
  `bearer` VARCHAR(250) NOT NULL,
  `idioma` VARCHAR(100) NULL DEFAULT NULL,
  `rul` VARCHAR(250) NOT NULL,
  `senha` VARCHAR(100) NULL DEFAULT NULL,
  `url` VARCHAR(250) NOT NULL,
  `usuario` VARCHAR(100) NULL DEFAULT NULL,
  `id_usuario_alterado` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario_criador` VARCHAR(255) NOT NULL,
  `id_configuracao` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK1p64fs1xaliewncm69y4a8aw7` (`id_configuracao` ASC) VISIBLE,
  INDEX `FKtn7nxu40kd4vccikdnql25x7g` (`id_usuario_alterado` ASC) VISIBLE,
  INDEX `FK4wqn1lmqyxe5tpqcf42qk013` (`id_usuario_criador` ASC) VISIBLE,
  CONSTRAINT `FK4wqn1lmqyxe5tpqcf42qk013`
    FOREIGN KEY (`id_usuario_criador`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FK8h9ykt5xdll412bpw5w87mc9f`
    FOREIGN KEY (`id_configuracao`)
    REFERENCES `tbl_configuracao` (`id`),
  CONSTRAINT `FKtn7nxu40kd4vccikdnql25x7g`
    FOREIGN KEY (`id_usuario_alterado`)
    REFERENCES `tbl_usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_mapa_perguntas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_mapa_perguntas` ;

CREATE TABLE IF NOT EXISTS `tbl_mapa_perguntas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `alterado` DATETIME(6) NULL DEFAULT NULL,
  `criado` DATETIME(6) NOT NULL,
  `ip_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_criador` VARCHAR(100) NOT NULL,
  `ip_proxy_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_proxy_criador` VARCHAR(100) NULL DEFAULT NULL,
  `status_dado` ENUM('APROVADO', 'NOVO', 'REMOVIDO', 'REPROVADO') NULL DEFAULT NULL,
  `data_sugestao_publicacao` DATE NULL DEFAULT NULL,
  `motivo_sugestao` VARCHAR(3000) NULL DEFAULT NULL,
  `ordem_relevancia` INT NULL DEFAULT NULL,
  `perfil_enquadra` VARCHAR(3000) NULL DEFAULT NULL,
  `pergunta` VARCHAR(250) NOT NULL,
  `stream` TEXT NULL DEFAULT NULL,
  `uuid_requisicao` VARCHAR(100) NULL DEFAULT NULL,
  `id_usuario_alterado` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario_criador` VARCHAR(255) NOT NULL,
  `id_categoria` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK6iq5r22t3hcjqq3n8vkr0uyty` (`id_usuario_alterado` ASC) VISIBLE,
  INDEX `FK9xmhf628cbg15euxkh4ll5ek8` (`id_usuario_criador` ASC) VISIBLE,
  INDEX `FK6at2bbxs6y1obm4j022w5apwh` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `FK6at2bbxs6y1obm4j022w5apwh`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `tbl_categoria` (`id`),
  CONSTRAINT `FK6iq5r22t3hcjqq3n8vkr0uyty`
    FOREIGN KEY (`id_usuario_alterado`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FK9xmhf628cbg15euxkh4ll5ek8`
    FOREIGN KEY (`id_usuario_criador`)
    REFERENCES `tbl_usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_materia` ;

CREATE TABLE IF NOT EXISTS `tbl_materia` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `alterado` DATETIME(6) NULL DEFAULT NULL,
  `criado` DATETIME(6) NOT NULL,
  `ip_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_criador` VARCHAR(100) NOT NULL,
  `ip_proxy_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_proxy_criador` VARCHAR(100) NULL DEFAULT NULL,
  `status_dado` ENUM('APROVADO', 'NOVO', 'REMOVIDO', 'REPROVADO') NULL DEFAULT NULL,
  `alias` VARCHAR(500) NULL DEFAULT NULL,
  `cricao_na_plataforma` DATETIME(6) NULL DEFAULT NULL,
  `exportado_para_plataforma` DATETIME(6) NULL DEFAULT NULL,
  `id_joomla` BIGINT NULL DEFAULT NULL,
  `id_wordpress` BIGINT NULL DEFAULT NULL,
  `keywords` VARCHAR(250) NULL DEFAULT NULL,
  `materia` TEXT NULL DEFAULT NULL,
  `meta_descircao` VARCHAR(250) NULL DEFAULT NULL,
  `introducao` VARCHAR(250) NULL DEFAULT NULL,
  `data_publicar` DATETIME(6) NULL DEFAULT NULL,
  `status` ENUM('ERRO', 'PROCESSADO', 'PROCESSAR') NULL DEFAULT NULL,
  `stream` TEXT NULL DEFAULT NULL,
  `tema_proposto` VARCHAR(250) NULL DEFAULT NULL,
  `titulo_1` VARCHAR(200) NULL DEFAULT NULL,
  `titulo_2` VARCHAR(200) NULL DEFAULT NULL,
  `titulo_3` VARCHAR(200) NULL DEFAULT NULL,
  `titulo_selecionado` INT NULL DEFAULT NULL,
  `uuid_requisicao` VARCHAR(100) NULL DEFAULT NULL,
  `id_usuario_alterado` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario_criador` VARCHAR(255) NOT NULL,
  `id_categoria` BIGINT NULL DEFAULT NULL,
  `id_configuracao` BIGINT NOT NULL,
  `id_mapa_pergunta` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `IDXl0s1btlen2c7orjnq0ktdsjha` (`titulo_1` ASC, `titulo_2` ASC, `titulo_3` ASC, `criado` ASC) VISIBLE,
  INDEX `IDXsb22hyflx7n2n5cpax5ei7huo` (`titulo_1` ASC, `titulo_2` ASC, `titulo_3` ASC) VISIBLE,
  INDEX `IDXb00ga2j62ggbqg8pi1lbf4awo` (`criado` ASC) VISIBLE,
  INDEX `FK18qhgcu1xtugr8y6dtubg64tc` (`id_usuario_alterado` ASC) VISIBLE,
  INDEX `FKjld5uvxbs264e7twt3l4sn5eq` (`id_usuario_criador` ASC) VISIBLE,
  INDEX `FKlya3s7h1f2xri63qkygoq1c8d` (`id_categoria` ASC) VISIBLE,
  INDEX `FKg4yusl8tft5wwuh14iufhjsmw` (`id_configuracao` ASC) VISIBLE,
  INDEX `FKhndfhxnwmhkmqd11wkn8ahxvc` (`id_mapa_pergunta` ASC) VISIBLE,
  CONSTRAINT `FK18qhgcu1xtugr8y6dtubg64tc`
    FOREIGN KEY (`id_usuario_alterado`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FKg4yusl8tft5wwuh14iufhjsmw`
    FOREIGN KEY (`id_configuracao`)
    REFERENCES `tbl_configuracao` (`id`),
  CONSTRAINT `FKhndfhxnwmhkmqd11wkn8ahxvc`
    FOREIGN KEY (`id_mapa_pergunta`)
    REFERENCES `tbl_mapa_perguntas` (`id`),
  CONSTRAINT `FKjld5uvxbs264e7twt3l4sn5eq`
    FOREIGN KEY (`id_usuario_criador`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FKlya3s7h1f2xri63qkygoq1c8d`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `tbl_categoria` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_dialogo_chatgpt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_dialogo_chatgpt` ;

CREATE TABLE IF NOT EXISTS `tbl_dialogo_chatgpt` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `completion_tokens` BIGINT NULL DEFAULT NULL,
  `resposta` TEXT NOT NULL,
  `created` BIGINT NULL DEFAULT NULL,
  `dt_criacao` DATETIME(6) NOT NULL,
  `finish_reason` VARCHAR(200) NULL DEFAULT NULL,
  `id_chatgpt` VARCHAR(200) NULL DEFAULT NULL,
  `index_chatgpt` INT NULL DEFAULT NULL,
  `dt_inicio_processamento` DATETIME(6) NOT NULL,
  `logprobs` VARCHAR(200) NULL DEFAULT NULL,
  `model` VARCHAR(200) NULL DEFAULT NULL,
  `objeto` VARCHAR(200) NULL DEFAULT NULL,
  `pergunta` TEXT NOT NULL,
  `prompt_tokens` BIGINT NULL DEFAULT NULL,
  `role` VARCHAR(200) NULL DEFAULT NULL,
  `system_fingerprint` VARCHAR(200) NULL DEFAULT NULL,
  `total_tokens` BIGINT NULL DEFAULT NULL,
  `uuid` VARCHAR(200) NOT NULL,
  `id_materia` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKiyvlk02qiyqsww7rvonmttwsv` (`id_materia` ASC) VISIBLE,
  CONSTRAINT `FKiyvlk02qiyqsww7rvonmttwsv`
    FOREIGN KEY (`id_materia`)
    REFERENCES `tbl_materia` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_faq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_faq` ;

CREATE TABLE IF NOT EXISTS `tbl_faq` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `alterado` DATETIME(6) NULL DEFAULT NULL,
  `criado` DATETIME(6) NOT NULL,
  `ip_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_criador` VARCHAR(100) NOT NULL,
  `ip_proxy_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_proxy_criador` VARCHAR(100) NULL DEFAULT NULL,
  `status_dado` ENUM('APROVADO', 'NOVO', 'REMOVIDO', 'REPROVADO') NULL DEFAULT NULL,
  `pergunta` VARCHAR(250) NOT NULL,
  `resposta` VARCHAR(250) NOT NULL,
  `uuid_requisicao` VARCHAR(250) NULL DEFAULT NULL,
  `id_usuario_alterado` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario_criador` VARCHAR(255) NOT NULL,
  `id_configuracao` BIGINT NOT NULL,
  `id_materia` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK2jckty1w3922kxffqqs794dol` (`id_usuario_alterado` ASC) VISIBLE,
  INDEX `FKs7isj3ny16uwa1lmmdsydree3` (`id_usuario_criador` ASC) VISIBLE,
  INDEX `FKj2yyl1na9upfv0na6yhagae12` (`id_configuracao` ASC) VISIBLE,
  INDEX `FKjyvq9wat1t1k0l67xckhxjhv6` (`id_materia` ASC) VISIBLE,
  CONSTRAINT `FK2jckty1w3922kxffqqs794dol`
    FOREIGN KEY (`id_usuario_alterado`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FKj2yyl1na9upfv0na6yhagae12`
    FOREIGN KEY (`id_configuracao`)
    REFERENCES `tbl_configuracao` (`id`),
  CONSTRAINT `FKjyvq9wat1t1k0l67xckhxjhv6`
    FOREIGN KEY (`id_materia`)
    REFERENCES `tbl_materia` (`id`),
  CONSTRAINT `FKs7isj3ny16uwa1lmmdsydree3`
    FOREIGN KEY (`id_usuario_criador`)
    REFERENCES `tbl_usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_feriados_fixos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_feriados_fixos` ;

CREATE TABLE IF NOT EXISTS `tbl_feriados_fixos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `data_feriado` DATE NOT NULL,
  `nome_feriado` VARCHAR(255) NOT NULL,
  `tipo` ENUM('DATA_COMEMORATIVA', 'FERIADO_NORMAL', 'OUTRO') NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_feriados_moveis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_feriados_moveis` ;

CREATE TABLE IF NOT EXISTS `tbl_feriados_moveis` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `data_feriado` DATE NOT NULL,
  `nome_feriado` VARCHAR(255) NOT NULL,
  `tipo` ENUM('DATA_COMEMORATIVA', 'FERIADO_NORMAL', 'OUTRO') NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_grupo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_grupo_usuario` ;

CREATE TABLE IF NOT EXISTS `tbl_grupo_usuario` (
  `id` VARCHAR(255) NOT NULL,
  `alterado` DATETIME(6) NULL DEFAULT NULL,
  `criado` DATETIME(6) NOT NULL,
  `ip_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_criador` VARCHAR(100) NOT NULL,
  `ip_proxy_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_proxy_criador` VARCHAR(100) NULL DEFAULT NULL,
  `status_dado` ENUM('APROVADO', 'NOVO', 'REMOVIDO', 'REPROVADO') NULL DEFAULT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `id_usuario_alterado` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario_criador` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKtnqir316fedkhyho1x8ri77i7` (`nome` ASC) VISIBLE,
  INDEX `FKjd0j1t1vmmglg7ll4brhrh4e0` (`id_usuario_alterado` ASC) VISIBLE,
  INDEX `FK8e4e4bx7l47ft84dcpyb8cd91` (`id_usuario_criador` ASC) VISIBLE,
  CONSTRAINT `FK8e4e4bx7l47ft84dcpyb8cd91`
    FOREIGN KEY (`id_usuario_criador`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FKjd0j1t1vmmglg7ll4brhrh4e0`
    FOREIGN KEY (`id_usuario_alterado`)
    REFERENCES `tbl_usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_permissao` ;

CREATE TABLE IF NOT EXISTS `tbl_permissao` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKrwdply7c46irf2085g0mekykp` (`nome` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_grupo_permissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_grupo_permissao` ;

CREATE TABLE IF NOT EXISTS `tbl_grupo_permissao` (
  `id_permissao` BIGINT NOT NULL,
  `id_grupo` VARCHAR(255) NOT NULL,
  INDEX `FKbxh4h79wbdg8k452gsmkhx71u` (`id_grupo` ASC) VISIBLE,
  INDEX `FKjcqyyshxoblg8nrhhmtrx71f8` (`id_permissao` ASC) VISIBLE,
  CONSTRAINT `FKbxh4h79wbdg8k452gsmkhx71u`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `tbl_grupo_usuario` (`id`),
  CONSTRAINT `FKjcqyyshxoblg8nrhhmtrx71f8`
    FOREIGN KEY (`id_permissao`)
    REFERENCES `tbl_permissao` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_mapa_subperguntas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_mapa_subperguntas` ;

CREATE TABLE IF NOT EXISTS `tbl_mapa_subperguntas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `alterado` DATETIME(6) NULL DEFAULT NULL,
  `criado` DATETIME(6) NOT NULL,
  `ip_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_criador` VARCHAR(100) NOT NULL,
  `ip_proxy_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_proxy_criador` VARCHAR(100) NULL DEFAULT NULL,
  `status_dado` ENUM('APROVADO', 'NOVO', 'REMOVIDO', 'REPROVADO') NULL DEFAULT NULL,
  `pergunta` VARCHAR(250) NOT NULL,
  `uuid_requisicao` VARCHAR(100) NULL DEFAULT NULL,
  `id_usuario_alterado` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario_criador` VARCHAR(255) NOT NULL,
  `id_mapa_pergunta` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK5thr41ab2bno61vxgq7nkeujo` (`id_usuario_alterado` ASC) VISIBLE,
  INDEX `FKlpqnx52g6gh7dyndnqsm71ogu` (`id_usuario_criador` ASC) VISIBLE,
  INDEX `FK6vxksxivggd7beidm41nocv9p` (`id_mapa_pergunta` ASC) VISIBLE,
  CONSTRAINT `FK5thr41ab2bno61vxgq7nkeujo`
    FOREIGN KEY (`id_usuario_alterado`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FK6vxksxivggd7beidm41nocv9p`
    FOREIGN KEY (`id_mapa_pergunta`)
    REFERENCES `tbl_mapa_perguntas` (`id`),
  CONSTRAINT `FKlpqnx52g6gh7dyndnqsm71ogu`
    FOREIGN KEY (`id_usuario_criador`)
    REFERENCES `tbl_usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_mapaperguntas_termo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_mapaperguntas_termo` ;

CREATE TABLE IF NOT EXISTS `tbl_mapaperguntas_termo` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `alterado` DATETIME(6) NULL DEFAULT NULL,
  `criado` DATETIME(6) NOT NULL,
  `ip_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_criador` VARCHAR(100) NOT NULL,
  `ip_proxy_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_proxy_criador` VARCHAR(100) NULL DEFAULT NULL,
  `status_dado` ENUM('APROVADO', 'NOVO', 'REMOVIDO', 'REPROVADO') NULL DEFAULT NULL,
  `termo` VARCHAR(250) NOT NULL,
  `uuid_requisicao` VARCHAR(100) NULL DEFAULT NULL,
  `id_usuario_alterado` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario_criador` VARCHAR(255) NOT NULL,
  `id_mapa_pergunta` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK76crbk2y30yakchgxfhni522` (`id_usuario_alterado` ASC) VISIBLE,
  INDEX `FKp0rpknljepfos49owdos912g8` (`id_usuario_criador` ASC) VISIBLE,
  INDEX `FK7xq16jd6665h16svsekteggnq` (`id_mapa_pergunta` ASC) VISIBLE,
  CONSTRAINT `FK76crbk2y30yakchgxfhni522`
    FOREIGN KEY (`id_usuario_alterado`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FK7xq16jd6665h16svsekteggnq`
    FOREIGN KEY (`id_mapa_pergunta`)
    REFERENCES `tbl_mapa_perguntas` (`id`),
  CONSTRAINT `FKp0rpknljepfos49owdos912g8`
    FOREIGN KEY (`id_usuario_criador`)
    REFERENCES `tbl_usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_materia_faqs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_materia_faqs` ;

CREATE TABLE IF NOT EXISTS `tbl_materia_faqs` (
  `materia_entity_id` BIGINT NOT NULL,
  `faqs_id` BIGINT NOT NULL,
  UNIQUE INDEX `UK6rqvde6nlsxh88qui4tfya7ya` (`faqs_id` ASC) VISIBLE,
  INDEX `FKltvsdsahbtge1mf7wy62e7d9r` (`materia_entity_id` ASC) VISIBLE,
  CONSTRAINT `FKltvsdsahbtge1mf7wy62e7d9r`
    FOREIGN KEY (`materia_entity_id`)
    REFERENCES `tbl_materia` (`id`),
  CONSTRAINT `FKmjlr3ej4298by2ndqi7tqrlf3`
    FOREIGN KEY (`faqs_id`)
    REFERENCES `tbl_faq` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_materia_log_processo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_materia_log_processo` ;

CREATE TABLE IF NOT EXISTS `tbl_materia_log_processo` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `stream_dados_materia` TEXT NOT NULL,
  `gerado_dados` DATETIME(6) NOT NULL,
  `gerado_materia` DATETIME(6) NOT NULL,
  `info_materia` TEXT NULL DEFAULT NULL,
  `stream_materia` TEXT NULL DEFAULT NULL,
  `id_configuracao` BIGINT NOT NULL,
  `id_materia` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK2j5k0y65gqnc4tevpfajnvcxh` (`id_configuracao` ASC) VISIBLE,
  INDEX `FKrrl9stpx56vx2n8gsuyr201yd` (`id_materia` ASC) VISIBLE,
  CONSTRAINT `FK2j5k0y65gqnc4tevpfajnvcxh`
    FOREIGN KEY (`id_configuracao`)
    REFERENCES `tbl_configuracao` (`id`),
  CONSTRAINT `FKrrl9stpx56vx2n8gsuyr201yd`
    FOREIGN KEY (`id_materia`)
    REFERENCES `tbl_materia` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_tag` ;

CREATE TABLE IF NOT EXISTS `tbl_tag` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `alterado` DATETIME(6) NULL DEFAULT NULL,
  `criado` DATETIME(6) NOT NULL,
  `ip_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_criador` VARCHAR(100) NOT NULL,
  `ip_proxy_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_proxy_criador` VARCHAR(100) NULL DEFAULT NULL,
  `status_dado` ENUM('APROVADO', 'NOVO', 'REMOVIDO', 'REPROVADO') NULL DEFAULT NULL,
  `alias` VARCHAR(250) NULL DEFAULT NULL,
  `id_joomla` BIGINT NULL DEFAULT NULL,
  `id_wordpress` BIGINT NULL DEFAULT NULL,
  `idioma` VARCHAR(250) NULL DEFAULT NULL,
  `titulo` VARCHAR(250) NOT NULL,
  `uuid_requisicao` VARCHAR(100) NULL DEFAULT NULL,
  `id_usuario_alterado` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario_criador` VARCHAR(255) NOT NULL,
  `id_configuracao` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKmycx1nnv707x6nqxdsgka1h4g` (`id_usuario_alterado` ASC) VISIBLE,
  INDEX `FKkb8311rc02yacd1fcsejuk4fn` (`id_usuario_criador` ASC) VISIBLE,
  INDEX `FK90dnb79s0ini35hpcjb39siko` (`id_configuracao` ASC) VISIBLE,
  CONSTRAINT `FK90dnb79s0ini35hpcjb39siko`
    FOREIGN KEY (`id_configuracao`)
    REFERENCES `tbl_configuracao` (`id`),
  CONSTRAINT `FKkb8311rc02yacd1fcsejuk4fn`
    FOREIGN KEY (`id_usuario_criador`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FKmycx1nnv707x6nqxdsgka1h4g`
    FOREIGN KEY (`id_usuario_alterado`)
    REFERENCES `tbl_usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_materia_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_materia_tags` ;

CREATE TABLE IF NOT EXISTS `tbl_materia_tags` (
  `id_tag` BIGINT NOT NULL,
  `tags_id` BIGINT NOT NULL,
  INDEX `FK9rgmqeajn1d0o260t7rlne9vg` (`tags_id` ASC) VISIBLE,
  INDEX `FK73gk8n7365mm422c5q6owoms6` (`id_tag` ASC) VISIBLE,
  CONSTRAINT `FK73gk8n7365mm422c5q6owoms6`
    FOREIGN KEY (`id_tag`)
    REFERENCES `tbl_materia` (`id`),
  CONSTRAINT `FK9rgmqeajn1d0o260t7rlne9vg`
    FOREIGN KEY (`tags_id`)
    REFERENCES `tbl_tag` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_termos_empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_termos_empresa` ;

CREATE TABLE IF NOT EXISTS `tbl_termos_empresa` (
  `id` VARCHAR(255) NOT NULL,
  `alterado` DATETIME(6) NULL DEFAULT NULL,
  `criado` DATETIME(6) NOT NULL,
  `ip_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_criador` VARCHAR(100) NOT NULL,
  `ip_proxy_alterador` VARCHAR(100) NULL DEFAULT NULL,
  `ip_proxy_criador` VARCHAR(100) NULL DEFAULT NULL,
  `status_dado` ENUM('APROVADO', 'NOVO', 'REMOVIDO', 'REPROVADO') NULL DEFAULT NULL,
  `nome` VARCHAR(250) NOT NULL,
  `id_usuario_alterado` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario_criador` VARCHAR(255) NOT NULL,
  `id_empresa` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKmym8cii3fxbcr2exay2ad7jo0` (`id_usuario_alterado` ASC) VISIBLE,
  INDEX `FK2kkxc397v71nskfr2dh9gbgvj` (`id_usuario_criador` ASC) VISIBLE,
  INDEX `FKk0v4trw0w3057jjtu4vjowd92` (`id_empresa` ASC) VISIBLE,
  CONSTRAINT `FK2kkxc397v71nskfr2dh9gbgvj`
    FOREIGN KEY (`id_usuario_criador`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FKk0v4trw0w3057jjtu4vjowd92`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `tbl_empresa` (`id`),
  CONSTRAINT `FKmym8cii3fxbcr2exay2ad7jo0`
    FOREIGN KEY (`id_usuario_alterado`)
    REFERENCES `tbl_usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_usuario_empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_usuario_empresa` ;

CREATE TABLE IF NOT EXISTS `tbl_usuario_empresa` (
  `id_empresa` VARCHAR(255) NOT NULL,
  `id_usuario` VARCHAR(255) NOT NULL,
  INDEX `FKjacf7sqg6wbb1nk88x9nyvcy1` (`id_usuario` ASC) VISIBLE,
  INDEX `FKkfhl5iiqfi7bc72bcx8jgglga` (`id_empresa` ASC) VISIBLE,
  CONSTRAINT `FKjacf7sqg6wbb1nk88x9nyvcy1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FKkfhl5iiqfi7bc72bcx8jgglga`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `tbl_empresa` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tbl_usuario_grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_usuario_grupo` ;

CREATE TABLE IF NOT EXISTS `tbl_usuario_grupo` (
  `id_usuario` VARCHAR(255) NOT NULL,
  `id_grupo` VARCHAR(255) NOT NULL,
  INDEX `FKm2q8clo9utv5lspv3yos3ghs1` (`id_grupo` ASC) VISIBLE,
  INDEX `FKiejsyprpu34t9b1ob3e7juoct` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `FKiejsyprpu34t9b1ob3e7juoct`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `tbl_usuario` (`id`),
  CONSTRAINT `FKm2q8clo9utv5lspv3yos3ghs1`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `tbl_grupo_usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
